name: Docker Image CI

on:
  push:
    branches: 
      - master
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #Login
    - name: Login to DockerHubb
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Build the image
    - name: Build and push the image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hikiantti/exercise3_1:latest
